// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KKhW80pQeeQf01Uo6mVOAMVsExgMTfw',
    appId: '1:823307885531:web:617548a6d92e65e60fe5fe',
    messagingSenderId: '823307885531',
    projectId: 'koy-nti',
    authDomain: 'koy-nti.firebaseapp.com',
    storageBucket: 'koy-nti.firebasestorage.app',
    measurementId: 'G-4EDCXWCP3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8mF9j2h4Rz66UnpJODbM7koFNjpWOpP8',
    appId: '1:823307885531:android:f4bb34befca9cf660fe5fe',
    messagingSenderId: '823307885531',
    projectId: 'koy-nti',
    storageBucket: 'koy-nti.firebasestorage.app',
  );
}
